cognitive-search:
  endpoint: "https://xxx.search.windows.net"
  key: "xxx"

cognitive-services:
  endpoint: "https://xxx.cognitiveservices.azure.com/"
  location: "xxx"
  key: "xxx"

storage-account:
  name: "xxx"
  connection-string: "xxx"
  key: "xxx"